config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  root 'accounts#index'
  resources :accounts do 
  	  resources :ad_units
		member do
   		 	get 'synhronize'
  		end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :ad_units, dependent: :destroy
  validates :login, presence: true
  validates :password, presence: true
end

app/models/ad_unit.rb
class AdUnit < ApplicationRecord
   belongs_to :account
   validates :url, presence: true
end
	

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
require "synhronize_worker"
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all.order('created_at DESC')  
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
      @ad_units = @account.ad_units
  end

  # GET /accounts/new
  def new 
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|

      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url}
      format.json { head :no_content }
    end
  end
  
  def synhronize
     @account = Account.find(params[:id])
     @account.status = 0
    SynhronizeWorker.perform_async(@account.id)
    respond_to do |format|
      format.html { redirect_to accounts_url}
      format.json { head :no_content }
    end
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:login, :password, :status, :error_message)
    end
end

app/controllers/ad_units_controller.rb
class AdUnitsController < ApplicationController
    before_action :set_ad_unit, only: [ :destroy]

  def index
    @ad_units = AdUnit.all
  end

  def new
    @ad_unit = AdUnit.new
  end 

  def create
    @account = Account.find(params[:account_id])
    @account.status = 0
    @account.save
    @ad_unit = @account.ad_units.create(ad_unit_params)
     respond_to do |format|
      if @ad_unit.save
        format.html { redirect_to @account}
        format.json { render :show, status: :created, location: @account }
      else
        
        format.json { render json: @ad_units.errors, status: :unprocessable_entity }
        format.html { redirect_to @account }
      end
    end
  end

  def destroy
    @account = Account.find(params[:account_id])
    @ad_unit = @account.ad_units.find(params[:id])
    unless (@ad_unit.status == 2 || @ad_unit.status == 1)
      @ad_unit.destroy
      respond_to do |format|
      format.html { redirect_to @account }
      format.json { head :no_content }
      end
    end
  end

  private
  def set_ad_unit
      @account = Account.find(params[:account_id])
      @ad_unit = @account.ad_units.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_unit_params
      params.require(:ad_unit).permit(:name, :url, :status, :error_message)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper

end

app/helpers/ad_units_helper.rb
module AdUnitsHelper
  def class_type(status)
    case status 
    when -1 
      return "label label-danger"
    when 0 
 	    return "label label-primary"
 	  when 1 
 	    return "label label-info"
 	  when 2 
	    return "label label-success"
 	  end  
  end

  def ad_unit_status_info(status)
    case status 
    when -1 
      return "Error"
    when 0 
 	    return "Not created"
    when 1 
 	    return " In progress" 
 	  when 2 
	    return "Created"
 	  end  
  end

   def account_status_info(status)
     case status
     when -1
      return "Error"
     when 0
       return "Not synhronized"
     when 1
       return "In progress"
     when 2
       return "Synhronized"
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
<%= render 'shared/error_messages', f: @account %>
  <div class = 'container'>
  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login, id: :account_login, size: '40x10' %>
  </div>

  <div class="field">
    <%= form.label :password %>

    <%= form.text_field :password, id: :account_password, size: '40x10' %>
  </div>
</div>
  <div class="actions">
    <%= form.submit class: "btn btn-success btn-default"%>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div align='center'>
<h2>Editing Account</h2>

<%= render 'form', account: @account %>

</div>

app/views/accounts/index.html.erb
  <div align="center">
  <h2>Accounts:</h2>
  <br>
  <% @accounts.each do |account| %>
      <div id="account" >
        <b><%= account.login %> </b> 
        <p class="text-danger"> <%= account.error_message %> </p>
        <%= link_to 'Show', account, class: "btn btn-info btn-xs" %>
        <%= link_to 'Edit', edit_account_path(account), class: "btn btn-success btn-xs" %>
        <%= link_to 'Delete', account, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs" %>
        <% unless (account.status == 2 || account.status ==1) %>
       <%= link_to 'Synhronize', synhronize_account_path(account), class: "btn btn-info btn-xs" %>
       <% end %>
        <br>
        <div class="<%=class_type(account.status)%>" > <%= account_status_info(account.status)%> </div>
        <br>
        <br>
      </div>

  <% end %>

</div>

app/views/accounts/new.html.erb
<div align="center">
<h2>New Account</h2>

<%= render 'form', account: @account %>

app/views/accounts/show.html.erb
<div align = "center">
  <h2><%= @account.login %></h2>

  <div id="ad_units"> 
    <%= render 'ad_units/index' %>
  </div>

  <br>

  <div>
    <%= render 'ad_units/new' %>
  </div>

</div>

app/views/ad_units/_ad_unit.html.erb
<div id="ad_unit_<%= @ad_unit_.id %>">
  <b><%= @ad_unit_name %></b> 
  <i><%= @comment.url %></i>
  <br>
   <% if ad_unit.status == 0 %>
       <%= link_to 'Delete', [comment.post, comment], method: :delete, class: "btn btn-danger btn-xs" %>
   <% end %>
</div>

app/views/ad_units/_index.html.erb
<h3>Ad units:</h3>
<% @account.ad_units.each do |ad_unit| %>
  <div id="ad_unit_<%= ad_unit.id %>">
    <b><%= ad_unit.name %> 
    <div class="<%=class_type(ad_unit.status)%>"> <%= ad_unit_status_info(ad_unit.status)%> </div>
     
    </b> 
      <% unless ad_unit.status == 2 %>
        <%= link_to 'Delete', [ad_unit.account, ad_unit], method: :delete, data: { confirm: 'Are you sure?' },  class:  "btn btn-danger btn-xs"%>
    <% end %>
    <br>
    <b><%= ad_unit.url %></b>
    <br>
   <p class="text-danger"> <%= ad_unit.error_message %>  </p>
  
    <br>
  </div>
<% end %>

app/views/ad_units/_new.html.erb
<h4>Add ad unit:</h4>
    <%= form_for [@account, @account.ad_units.build] do |f| %>
        <div class="field" id = "new_ad_unit_name">
          <%= f.label :name %>
          <%= f.text_field :name, size: '40x10' %>
        </div>  
        <div class="field" id = "new_ad_unit_url">
         <%= f.label :url %>
          <%= f.text_field :url, size: '40x10'%>
        </div>
        <div class="actions">
          <%= f.submit 'Submit', class: "btn btn-success btn-default" %>
        </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Robot</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true  %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true  %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render 'shared/navbar' %>
  	<div align="center">
  		<%= flash[:alert]  %>
  	</div>
    <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
 
<% if f.errors.any? %>
  <div id="error_explanation"> 
    <div class="alert alert-danger">
      The form contains <%= pluralize(f.errors.count, "error") %>.
    </div>
     <ul class="list-unstyled">
      <% f.errors.full_messages.each do |msg| %>
      <li><p class="text-danger"><%= msg %></p></li>
      <% end %>
    </ul>
    </ul>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Authorization robot</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><%= link_to 'All accounts', root_url %></li>

        <li><%= link_to 'New Account', new_account_path %></li>

      </ul>

      <ul class="nav navbar-nav navbar-text">

            <span class="text-danger">Welcome!</span>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>